name: manual release

on: workflow_dispatch

jobs:
  release-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.5.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Release Canary
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pnpx dripip stable --json > result.json
          jq '.' < result.json
